steps:
  # 0. Download weights from GCS (parallel download with -m)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Download Model Weights'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mkdir -p models && gsutil -m cp -r gs://modeles-triage-hospitalier/merged_dpo_final_chsa ./models/'

  # 1. Construction de l'image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-f', 'Dockerfile.cloudrun', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/mon-depot-modeles/agent-triage:$COMMIT_SHA', '.']

  # 2. Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agent-triage-service'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mon-depot-modeles/agent-triage:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region=europe-west1' # Utiliser une substitution est encore mieux
      - '--startup-probe-path=/health'
      - '--startup-probe-port=8080'

# Utilisation du champ 'images' pour automatiser le push vers AR
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mon-depot-modeles/agent-triage:$COMMIT_SHA'
