# Utiliser une image Python de base adaptée à la version 3.12
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer uv pour la gestion des dépendances
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copier les fichiers de configuration du projet
COPY pyproject.toml uv.lock ./

# Synchroniser les dépendances (sans les dépendances de dev)
RUN uv sync --no-dev --no-editable

# --- AJOUT : Téléchargement des modèles SpaCy ---
RUN .venv/bin/python -m spacy download fr_core_news_lg
RUN .venv/bin/python -m spacy download en_core_web_lg

# Copier tout le code de l'application
COPY . .

# Définir PYTHONPATH pour inclure le répertoire racine
ENV PYTHONPATH=/app

# Utiliser l'environnement virtuel créé par uv
ENV PATH="/app/.venv/bin:$PATH"

# Commande pour lancer l'application avec Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
