FROM python:3.11-slim
WORKDIR /app
COPY ui_streamlit.py /app/ui_streamlit.py
COPY requirements.txt /app/requirements.txt
# Installation des dépendances et de streamlit explicitement
RUN pip install --no-cache-dir -r requirements.txt streamlit
EXPOSE 8080
# Appel via python -m pour éviter les problèmes de PATH
CMD ["python", "-m", "streamlit", "run", "ui_streamlit.py", "--server.port=8080", "--server.address=0.0.0.0"]
