# Utilisation de l'image de base qui contient déjà python et les outils nécessaires
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Installation de curl et git
RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copier les fichiers de dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- ÉTAPE : Copie des modèles (préalablement téléchargés par Cloud Build) ---
RUN mkdir -p /app/models
COPY ./models /app/models

# Copier le code de l'application
COPY ./app /app/app

# Exposition du port
EXPOSE 8080

# Commande de lancement
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
