# Utiliser une image Python de base
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer uv, un gestionnaire de paquets et d'environnement virtuel rapide
RUN pip install uv

# Copier les fichiers de dépendances
COPY pyproject.toml poetry.lock* ./
COPY requirements.txt ./

# Installer les dépendances Python en utilisant uv pour la vitesse
RUN uv pip install --no-cache --system -r requirements.txt

# --- AJOUT : Téléchargement des modèles SpaCy ---
# Télécharger les modèles linguistiques requis par MedicalAnonymizer
RUN python -m spacy download fr_core_news_lg
RUN python -m spacy download en_core_web_lg

# Copier le reste du code de l'application
COPY ./app ./app

# Commande pour lancer l'application avec Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]